<?php
use AranduGo\Support;
$logoStyle='height:'.min(250,max(28,(int)($d['header']['logoSize']??36))).'px;'.(!empty($d['header']['maintainAspect'])?'width:auto':'width:'.max(40,(int)($d['header']['logoWidth']??180)).'px');
$labels=['home'=>'Inicio','services'=>'Servicios','gallery'=>'Galería','about'=>'Nosotros','free1'=>$d['freeSections'][0]['menuLabel']??'Más información','free2'=>$d['freeSections'][1]['menuLabel']??'Más información 2','contact'=>'Contacto'];$anchors=['home'=>'inicio','services'=>'servicios','gallery'=>'galeria','about'=>'nosotros','free1'=>'free1','free2'=>'free2','contact'=>'contacto'];$active=[];foreach($d['modules']??[] as $m)if(!empty($m['active']))$active[$m['key']]=true;$map=['services'=>'services','gallery'=>'gallery','about'=>'about','free1'=>'free1','free2'=>'free2','contact'=>'contact'];$main=[];$sub=[];foreach($d['menuOrder']??[] as $key){$cfg=$d['menuSettings'][$key]??['visible'=>true,'parent'=>null];if($key!=='home'&&empty($cfg['visible']))continue;if(isset($map[$key])&&empty($active[$map[$key]]))continue;if(($cfg['parent']??null)==='about')$sub[]=$key;else $main[]=$key;}$nav='';foreach($main as $key){if($key==='about'){$nav.='<details class="submenu"><summary>Nosotros</summary><div><a href="'.Support::url().'#nosotros">Acerca de</a>';foreach($sub as $child)$nav.='<a href="'.Support::url().'#'.($anchors[$child]??$child).'">'.Support::e($labels[$child]??$child).'</a>';if(!empty($d['legal']['showInHeaderMenu']))$nav.='<a href="'.Support::url('terminos.php').'">Términos</a><a href="'.Support::url('privacidad.php').'">Privacidad</a>';$nav.='</div></details>';}else $nav.='<a href="'.Support::url().'#'.($anchors[$key]??$key).'">'.Support::e($labels[$key]??$key).'</a>';}$wa=null;foreach($d['phones']??[] as $phone)if(($phone['type']??'')==='whatsapp'&&!empty($phone['number'])){$wa=$phone;break;}
?>
<header class="site-header" style="background:<?=Support::e($d['header']['background']??'#fff')?>;color:<?=Support::e($d['header']['text']??'#172033')?>">
 <a class="identity" href="<?=Support::url()?>"><?php if(($d['header']['identityType']??'initial')==='logo'&&!empty($d['header']['logo'])):?><img src="<?=Support::e($d['header']['logo'])?>" alt="Logo" style="<?=$logoStyle?>"><?php else:?><span class="identity-mark"><?=Support::e($d['header']['initial']??'A')?></span><?php endif;?><?php if(!empty($d['header']['showName'])):?><span><?=Support::e($d['header']['nameText']??$d['business']['name'])?></span><?php endif;?></a>
 <button class="button alt menu-toggle" type="button" aria-controls="mainMenu" aria-expanded="false">Menú</button><nav id="mainMenu"><?=$nav?></nav><?php if($wa):?><a class="button" href="https://wa.me/<?=preg_replace('/\D+/','',$wa['number'])?>"><i class="fa-brands fa-whatsapp"></i> WhatsApp</a><?php endif;?>
</header>
