"use client";
import { useState } from "react";
import Script from "next/script";
import { Send } from "lucide-react";

type CaptchaType="none"|"integrated"|"google_v2";
type Challenge="math"|"checkbox"|"question";

export default function ContactForm({captchaType="integrated",googleSiteKey="",challengeMethod="math",challengeQuestion="¿Cuál es el color del cielo en un día despejado?"}:{captchaType?:CaptchaType;googleSiteKey?:string;challengeMethod?:Challenge;challengeQuestion?:string}){
 const [a]=useState(()=>Math.floor(Math.random()*5)+2);const [b]=useState(()=>Math.floor(Math.random()*5)+1);const [status,setStatus]=useState("");const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setStatus("");const f=new FormData(e.currentTarget);const answer=challengeMethod==="checkbox"?String(f.get("human")==="on"):String(f.get("answer")??"");const r=await fetch("/api/contact",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:f.get("name"),email:f.get("email"),phone:f.get("phone"),message:f.get("message"),website:f.get("website"),captchaType,challengeMethod,a,b,answer,recaptchaToken:f.get("g-recaptcha-response")})});const x=await r.json();setStatus(r.ok?(x.delivered?"Gracias. Tu mensaje fue enviado.":"Gracias. Registramos tu consulta."):x.error);if(r.ok)e.currentTarget.reset();setBusy(false)}
 const integrated=captchaType==="integrated";
 return <><form className="contact-form" onSubmit={submit}><div className="contact-form-grid"><label>Nombre<input name="name" required/></label><label>Correo electrónico<input name="email" type="email" required/></label><label>Teléfono<input name="phone" type="tel"/></label><label className="honeypot">Sitio web<input name="website" tabIndex={-1} autoComplete="off"/></label></div><label>Mensaje<textarea name="message" required minLength={5}/></label>{integrated&&challengeMethod==="math"&&<label className="captcha-row"><span>Verificación: ¿cuánto es {a} + {b}?</span><input name="answer" type="number" required inputMode="numeric"/></label>}{integrated&&challengeMethod==="question"&&<label className="captcha-row"><span>{challengeQuestion}</span><input name="answer" required autoComplete="off"/></label>}{integrated&&challengeMethod==="checkbox"&&<label className="captcha-check"><input name="human" type="checkbox" required/><span>Confirmo que soy una persona</span></label>}{captchaType==="google_v2"&&(googleSiteKey?<div className="g-recaptcha" data-sitekey={googleSiteKey}/>:<p className="captcha-warning">Google reCAPTCHA requiere configurar la clave pública.</p>)}<div className="contact-submit"><button disabled={busy}><Send/>{busy?"Enviando…":"Enviar consulta"}</button>{status&&<p role="status">{status}</p>}</div></form>{captchaType==="google_v2"&&googleSiteKey&&<Script src="https://www.google.com/recaptcha/api.js" strategy="afterInteractive"/>}</>
}
