import { type ModuleConfig } from "@/lib/site-data";
import { getPublished } from "@/lib/published";
import type { Metadata } from "next";
import { Clock3, Mail, MapPin, Wrench } from "lucide-react";
import PublicGallery from "./PublicGallery";
import SocialIcons from "./SocialIcons";
import ContactForm from "./ContactForm";
import { SiteFooter, SiteHeader } from "./SiteChrome";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faWhatsapp } from "@fortawesome/free-brands-svg-icons";
import PhoneIcon from "./PhoneIcon";
import AnalyticsCode from "./AnalyticsCode";

export const dynamic = "force-dynamic";
function safeHtml(html:string){return html.replace(/<(script|style|iframe)[\s\S]*?<\/\1>/gi,"").replace(/\son\w+\s*=\s*["'][^"']*["']/gi,"").replace(/javascript:/gi,"")}
function youtubeEmbed(url:string){const match=url.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/|shorts\/))([\w-]{6,})/);return match?`https://www.youtube-nocookie.com/embed/${match[1]}`:""}
function isWhatsappCta(label:string,url:string){return /whats?app/i.test(label)||/wa\.me|whatsapp\.com/i.test(url)}
function phoneHref(type:string,number:string){const clean=number.replace(/[^\d+]/g,"");return type==="whatsapp"?`https://wa.me/${clean.replace(/\D/g,"")}`:`tel:${clean}`}
function quickCell(code:string|undefined){const match=code?.toUpperCase().match(/^([A-D])([1-4])$/);return match?{gridRow:String(match[1].charCodeAt(0)-64),gridColumn:match[2]}:{}}
export async function generateMetadata():Promise<Metadata>{const data=await getPublished();return {title:`${data.business.name} — ${data.business.category}`,description:data.business.description,robots:data.seo.allowIndexing?{index:true,follow:true}:{index:false,follow:false,nocache:true}}}

export default async function Home() {
  const data = await getPublished();
  const byKey = Object.fromEntries(data.modules.map((m) => [m.key, m]));
  const style = (m: ModuleConfig) => ({ backgroundColor: m.background, color: m.text, "--accent": m.accent } as React.CSSProperties);
  const whatsapp=data.phones.find(p=>p.type==="whatsapp")??data.phones.find(p=>p.type==="mobile");
  const callable=data.phones.find(p=>p.type!=="whatsapp")??data.phones[0];
  const quickCards=data.quickOrder.flatMap(key=>{if(key==="address")return data.quickVisible.address&&data.business.address?[{key,icon:<MapPin/>,label:"Dirección",value:data.business.address}]:[];if(key==="hours")return data.quickVisible.hours&&data.business.hours?[{key,icon:<Clock3/>,label:"Horarios",value:data.business.hours}]:[];if(key==="email")return data.quickVisible.email&&data.business.email?[{key,icon:<Mail/>,label:"Correo",value:data.business.email}]:[];const phone=data.phones.find(p=>`phone:${p.id}`===key);return phone?.showInQuick&&phone.number?[{key,icon:<PhoneIcon type={phone.type}/>,label:phone.label||phone.type,value:phone.number}]:[]});
  const sections: Record<string, React.ReactNode> = {
    hero: <section id="inicio" className={`public-section hero-section ${data.hero.showImage&&data.hero.image?"":"without-image"}`} style={style(byKey.hero)}><div>{data.hero.showCategory&&data.business.category&&<span className="eyebrow">{data.business.category}</span>}{data.hero.showTitle&&data.hero.title&&<h1>{data.hero.title}</h1>}{data.hero.showText&&data.hero.text&&<p>{data.hero.text}</p>}<div className="action-row">{data.hero.showWhatsappCta&&whatsapp?.number&&<a className="primary-action whatsapp-cta" href={phoneHref("whatsapp",whatsapp.number)}><FontAwesomeIcon icon={faWhatsapp}/>WhatsApp</a>}{data.hero.showCallCta&&callable?.number&&<a className="secondary-action" href={phoneHref(callable.type,callable.number)}><PhoneIcon type={callable.type}/>Llamar</a>}{data.hero.showMapsCta&&data.business.mapsUrl&&<a className="secondary-action" href="#ubicacion">Cómo llegar</a>}</div></div>{data.hero.showImage&&data.hero.image&&<img src={data.hero.image} alt={data.business.name} />}</section>,
    quick: <section className={`public-section quick-grid quick-${data.quickLayout.placement}`} style={{...style(byKey.quick),gridTemplateColumns:`repeat(${data.quickLayout.columns},1fr)`,"--quick-columns":data.quickLayout.columns} as React.CSSProperties}>{quickCards.slice(0,data.quickLayout.rows*data.quickLayout.columns).map(card=><div key={card.key} style={data.quickLayout.placement==="manual"?quickCell(data.quickLayout.positions[card.key]):undefined}>{card.icon}<strong>{card.label}</strong><span>{card.value}</span></div>)}</section>,
    about: <section id="nosotros" className="public-section split-copy without-number" style={style(byKey.about)}><div><p className="eyebrow">Sobre el negocio</p><h2>{data.about.title}</h2><p>{data.about.text}</p></div></section>,
    services: <section id="servicios" className="public-section" style={style(byKey.services)}><div className="section-heading"><div><p className="eyebrow">Lo que hacemos</p><h2>Servicios y productos</h2></div><Wrench/></div><div className="service-grid">{data.services.map((s,i)=><article key={s.id}><span>{String(i+1).padStart(2,"0")}</span><h3>{s.title}</h3><p>{s.description}</p></article>)}</div></section>,
    gallery: <section id="galeria" className="public-section" style={style(byKey.gallery)}><div className="section-heading"><div><p className="eyebrow">Galería</p><h2>Conocé nuestro trabajo</h2></div><span>{data.gallery.filter(x=>x.visible).length} fotos</span></div><PublicGallery items={data.gallery} rows={data.galleryLayout.rows} columns={data.galleryLayout.columns}/></section>,
    location: <section id="ubicacion" className="public-section location-grid" style={style(byKey.location)}><iframe className="google-map" src={data.business.mapsEmbedUrl} loading="lazy" referrerPolicy="no-referrer-when-downgrade" title={`Mapa de ${data.business.name}`}/><div><p className="eyebrow">Ubicación y horarios</p><h2>Estamos cerca</h2><p>{data.business.address}</p><p>{data.business.hours}</p><a className="secondary-action" href={data.business.mapsUrl} target="_blank" rel="noreferrer"><MapPin/> Abrir mapa</a></div></section>,
    contact: <section id="contacto" className="public-section contact-section" style={style(byKey.contact)}><div className="contact-intro"><p className="eyebrow">Contacto</p><h2>¿Tenés alguna consulta?</h2><p>Elegí el canal que te resulte más cómodo o dejanos tu mensaje.</p><div className="contact-methods">{data.phones.filter(p=>p.showInContact&&p.number).map(phone=><a key={phone.id} href={phoneHref(phone.type,phone.number)}><PhoneIcon type={phone.type}/><span><small>{phone.label}</small><strong>{phone.number}</strong></span></a>)}<a href={`mailto:${data.business.email}`}><Mail/> <span><small>Correo</small><strong>{data.business.email}</strong></span></a></div></div>{data.contactForm.enabled&&<ContactForm captchaType={data.contactForm.captchaType} googleSiteKey={data.contactForm.googleSiteKey} challengeMethod={data.contactForm.challengeMethod} challengeQuestion={data.contactForm.challengeQuestion}/>}</section>,
    social: <section className="public-section social-band" style={style(byKey.social)}><strong>Seguinos</strong><SocialIcons socials={data.socials} customSocial={data.customSocial}/></section>,
    free1: null,
    free2: null,
  };
  for(const free of data.freeSections){const m=byKey[free.id];sections[free.id]=<section id={free.id} className="public-section free-section" style={style(m)}><div><p className="eyebrow">Sección especial</p><h2>{free.title}</h2><div className="rich-public" dangerouslySetInnerHTML={{__html:safeHtml(free.html)}}/>{free.ctaLabel&&<a className="primary-action" href={free.ctaUrl}>{isWhatsappCta(free.ctaLabel,free.ctaUrl)&&<FontAwesomeIcon icon={faWhatsapp}/>} {free.ctaLabel}</a>}</div>{free.media.length>0&&<div className="free-images">{free.media.map((media,i)=>media.type==="image"?<figure key={media.id}><img src={media.url} alt={media.caption||`${free.title} ${i+1}`}/>{media.caption&&<figcaption>{media.caption}</figcaption>}</figure>:youtubeEmbed(media.url)?<figure key={media.id} className="video-frame"><iframe src={youtubeEmbed(media.url)} title={media.caption||`Video ${i+1}`} loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/>{media.caption&&<figcaption>{media.caption}</figcaption>}</figure>:null)}</div>}</section>}
  return <div className="public-shell">{data.customCode.css&&<style dangerouslySetInnerHTML={{__html:data.customCode.css}}/>}<AnalyticsCode code={data.customCode.analytics}/><SiteHeader data={data}/><main>{data.modules.filter(m=>m.active).map(m=><div key={m.key}>{sections[m.key]}</div>)}</main><SiteFooter data={data}/><div className="mobile-actions">{whatsapp&&<a href={phoneHref("whatsapp",whatsapp.number)}><FontAwesomeIcon icon={faWhatsapp}/> WhatsApp</a>}{callable&&<a href={phoneHref(callable.type,callable.number)}><PhoneIcon type={callable.type}/> Llamar</a>}{data.business.mapsUrl&&byKey.location?.active&&<a href="#ubicacion">Cómo llegar</a>}</div></div>;
}
