<?php
require __DIR__.'/bootstrap.php';
use AranduGo\SiteRepository; use AranduGo\Support;
$d=SiteRepository::published(); $modules=array_values(array_filter($d['modules']??[],fn($m)=>!empty($m['active']))); $by=[]; foreach($modules as $m)$by[$m['key']]=$m;
$style=fn(string $key)=>isset($by[$key])?'--bg:'.Support::e($by[$key]['background']).';--text:'.Support::e($by[$key]['text']).';--accent:'.Support::e($by[$key]['accent']):'';
$phoneHref=function(array $p):string{$n=preg_replace('/\D+/','',$p['number']??'');return ($p['type']??'')==='whatsapp'?'https://wa.me/'.$n:'tel:+'.$n;};
$phones=$d['phones']??[];$wa=current(array_filter($phones,fn($p)=>($p['type']??'')==='whatsapp'&&!empty($p['number'])))?:null;$call=current(array_filter($phones,fn($p)=>in_array($p['type']??'', ['mobile','landline'],true)&&!empty($p['number'])))?:null;
$menuLabels=['home'=>'Inicio','services'=>'Servicios','gallery'=>'Galería','about'=>'Nosotros','free1'=>$d['freeSections'][0]['menuLabel']??'Más información','free2'=>$d['freeSections'][1]['menuLabel']??'Más información 2','contact'=>'Contacto'];
$anchors=['home'=>'inicio','services'=>'servicios','gallery'=>'galeria','about'=>'nosotros','free1'=>'free1','free2'=>'free2','contact'=>'contacto'];
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=Support::e($d['business']['name']??'Arandu Go')?></title><meta name="robots" content="<?=!empty($d['seo']['allowIndexing'])?'index,follow':'noindex,nofollow'?>"><link rel="stylesheet" href="<?=Support::url('assets/site.css')?>"><?php if(!empty($d['customCode']['css'])):?><style><?=$d['customCode']['css']?></style><?php endif;?></head><body id="inicio">
<header class="site-header" style="background:<?=Support::e($d['header']['background']??'#fff')?>;color:<?=Support::e($d['header']['text']??'#172033')?>"><a class="identity" href="#inicio"><?php if(($d['header']['identityType']??'initial')==='logo'&&!empty($d['header']['logo'])):?><img src="<?=Support::e($d['header']['logo'])?>" alt="Logo" style="height:<?=min(250,max(28,(int)$d['header']['logoSize']))?>px;<?=!empty($d['header']['maintainAspect'])?'width:auto':'width:'.(int)$d['header']['logoWidth'].'px'?>"><?php else:?><span class="identity-mark"><?=Support::e($d['header']['initial']??'A')?></span><?php endif;?><?php if(!empty($d['header']['showName'])):?><span><?=Support::e($d['header']['nameText']??$d['business']['name'])?></span><?php endif;?></a><button class="button alt menu-toggle" type="button" aria-label="Abrir menú">Menú</button><nav id="mainMenu"><?php foreach($d['menuOrder']??[] as $key):$setting=$d['menuSettings'][$key]??['visible'=>true];if($key!=='home'&&empty($setting['visible']))continue;?><a href="#<?=Support::e($anchors[$key]??$key)?>"><?=Support::e($menuLabels[$key]??$key)?></a><?php endforeach;?></nav><?php if($wa):?><a class="button" href="<?=$phoneHref($wa)?>">◉ WhatsApp</a><?php endif;?></header><main>
<?php foreach($modules as $m):$key=$m['key']; if($key==='hero'):?><section class="section hero" style="<?=$style('hero')?>"><div><p class="eyebrow"><?=Support::e($d['business']['category']??'')?></p><h1><?=Support::e($d['hero']['title']??'')?></h1><p><?=Support::e($d['hero']['text']??'')?></p><div class="cta-row"><?php if(!empty($d['hero']['showWhatsappCta'])&&$wa):?><a class="button" href="<?=$phoneHref($wa)?>">◉ WhatsApp</a><?php endif;?><?php if(!empty($d['hero']['showCallCta'])&&$call):?><a class="button alt" href="<?=$phoneHref($call)?>">☎ Llamar</a><?php endif;?><?php if(!empty($d['hero']['showMapsCta'])&&!empty($d['business']['mapsUrl'])):?><a class="button alt" href="#ubicacion">Cómo llegar</a><?php endif;?></div></div><?php if(!empty($d['hero']['showImage'])&&!empty($d['hero']['image'])):?><div class="hero-media"><img src="<?=Support::e($d['hero']['image'])?>" alt="<?=Support::e($d['business']['name'])?>"></div><?php endif;?></section>
<?php elseif($key==='quick'):?><section class="section" style="<?=$style('quick')?>"><div class="quick-grid" style="--cols:<?=max(1,min(4,(int)($d['quickLayout']['columns']??3)))?>"><?php foreach($d['quickOrder']??[] as $item):if($item==='address'&&!empty($d['quickVisible']['address'])):?><article class="card"><strong>⌖ Dirección</strong><p><?=Support::e($d['business']['address'])?></p></article><?php elseif($item==='hours'&&!empty($d['quickVisible']['hours'])):?><article class="card"><strong>◷ Horarios</strong><p><?=Support::e($d['business']['hours'])?></p></article><?php elseif($item==='email'&&!empty($d['quickVisible']['email'])):?><article class="card"><strong>✉ Correo</strong><p><?=Support::e($d['business']['email'])?></p></article><?php elseif(str_starts_with($item,'phone:')):$id=substr($item,6);foreach($phones as $p)if($p['id']===$id&&!empty($p['showInQuick'])&&!empty($p['number'])):?><a class="card" href="<?=$phoneHref($p)?>"><strong><?=($p['type']==='whatsapp'?'◉':($p['type']==='mobile'?'▣':'☎'))?> <?=Support::e($p['label'])?></strong><p><?=Support::e($p['number'])?></p></a><?php endif;endforeach;endif;endforeach;?></div></section>
<?php elseif($key==='about'):?><section id="nosotros" class="section" style="<?=$style('about')?>"><p class="eyebrow">Sobre el negocio</p><h2><?=Support::e($d['about']['title']??'')?></h2><p><?=nl2br(Support::e($d['about']['text']??''))?></p></section>
<?php elseif($key==='services'):?><section id="servicios" class="section" style="<?=$style('services')?>"><p class="eyebrow">Servicios / Productos</p><h2>Lo que ofrecemos</h2><div class="service-grid"><?php foreach($d['services']??[] as $s):?><article class="card"><h3><?=Support::e($s['title'])?></h3><p><?=Support::e($s['description'])?></p></article><?php endforeach;?></div></section>
<?php elseif($key==='gallery'):?><section id="galeria" class="section" style="<?=$style('gallery')?>"><p class="eyebrow">Galería</p><h2>Imágenes del negocio</h2><div class="gallery-grid" style="--cols:<?=max(1,min(4,(int)($d['galleryLayout']['columns']??3)))?>"><?php foreach(array_filter($d['gallery']??[],fn($g)=>!empty($g['visible'])) as $g):?><article class="card gallery-card"><img src="<?=Support::e($g['image'])?>" alt="<?=Support::e($g['title'])?>"><div><h3><?=Support::e($g['title'])?></h3><p><?=Support::e($g['description'])?></p><?php if(!empty($g['ctaLabel'])&&!empty($g['ctaUrl'])):?><a class="button" href="<?=Support::e($g['ctaUrl'])?>"><?=Support::e($g['ctaLabel'])?></a><?php endif;?></div></article><?php endforeach;?></div></section>
<?php elseif($key==='location'):?><section id="ubicacion" class="section location-grid" style="<?=$style('location')?>"><iframe class="map" src="<?=Support::e($d['business']['mapsEmbedUrl']??'')?>" loading="lazy"></iframe><div><p class="eyebrow">Ubicación</p><h2>¿Cómo llegar?</h2><p><?=Support::e($d['business']['address']??'')?></p><p><?=Support::e($d['business']['hours']??'')?></p><?php if(!empty($d['business']['mapsUrl'])):?><a class="button" target="_blank" rel="noopener" href="<?=Support::e($d['business']['mapsUrl'])?>">Abrir mapa</a><?php endif;?></div></section>
<?php elseif($key==='contact'):?><section id="contacto" class="section contact-grid" style="<?=$style('contact')?>"><div><p class="eyebrow">Contacto</p><h2>¿Tenés alguna consulta?</h2><?php foreach(array_filter($phones,fn($p)=>!empty($p['showInContact'])&&!empty($p['number'])) as $p):?><p><a href="<?=$phoneHref($p)?>"><strong><?=Support::e($p['label'])?>:</strong> <?=Support::e($p['number'])?></a></p><?php endforeach;?><p><a href="mailto:<?=Support::e($d['business']['email']??'')?>"><?=Support::e($d['business']['email']??'')?></a></p></div><?php if(!empty($d['contactForm']['enabled'])):?><form class="contact-form" method="post" action="<?=Support::url('contact.php')?>"><input name="name" placeholder="Nombre" required><input type="email" name="email" placeholder="Correo" required><input name="phone" placeholder="Teléfono"><textarea name="message" placeholder="Mensaje" required></textarea><input name="website" tabindex="-1" autocomplete="off" style="position:absolute;left:-9999px"><?php if(($d['contactForm']['captchaType']??'none')==='integrated'):?><label><input type="checkbox" name="human" value="1" required> Soy una persona</label><?php endif;?><button class="button">Enviar consulta</button></form><?php endif;?></section>
<?php elseif($key==='social'):?><section class="section" style="<?=$style('social')?>"><p class="eyebrow">Redes sociales</p><h2>Seguinos</h2><div class="social-row"><?php foreach($d['socials']??[] as $network=>$url)if($url):?><a href="<?=Support::e($url)?>" target="_blank" rel="noopener"><?=Support::e(ucfirst($network))?></a><?php endforeach;?></div></section>
<?php elseif(in_array($key,['free1','free2'],true)):$free=current(array_filter($d['freeSections']??[],fn($f)=>$f['id']===$key));if($free):?><section id="<?=$key?>" class="section" style="<?=$style($key)?>"><p class="eyebrow"><?=Support::e($free['publicLabel']??'Información')?></p><h2><?=Support::e($free['title'])?></h2><div><?=$free['html']?></div><?php foreach($free['media']??[] as $media):?><?php if($media['type']==='image'):?><img src="<?=Support::e($media['url'])?>" alt="<?=Support::e($media['caption'])?>"><?php endif;?><?php endforeach;?><?php if(!empty($free['ctaLabel'])&&!empty($free['ctaUrl'])):?><a class="button" href="<?=Support::e($free['ctaUrl'])?>"><?=Support::e($free['ctaLabel'])?></a><?php endif;?></section><?php endif;endif;endforeach;?></main>
<footer class="site-footer" style="background:<?=Support::e($d['footer']['background']??'#fff')?>;color:<?=Support::e($d['footer']['text']??'#526078')?>"><p><?=Support::e($d['footer']['legalText']??'')?></p><?php if(!empty($d['footer']['showLegalLinks'])):?><a href="<?=Support::url('terminos.php')?>">Términos</a><a href="<?=Support::url('privacidad.php')?>">Privacidad</a><?php endif;?></footer><div class="mobile-actions"><?php if($wa):?><a href="<?=$phoneHref($wa)?>">◉ WhatsApp</a><?php endif;?><?php if($call):?><a href="<?=$phoneHref($call)?>">☎ Llamar</a><?php endif;?><a href="#ubicacion">⌖ Cómo llegar</a></div><script>document.querySelector('.menu-toggle')?.addEventListener('click',()=>document.querySelector('#mainMenu').classList.toggle('open'));</script><?=$d['customCode']['analytics']??''?></body></html>
