"use client";
import { useEffect, useState } from "react";
import { Download, Mail, RefreshCw } from "lucide-react";
import { Switch } from "@/components/ui/switch";
import type { SiteData } from "@/lib/site-data";

type LogRow={id:string;name:string;email:string;createdAt:string;timezone:string;delivered:boolean};
export default function FormSettings({data,onChange}:{data:SiteData;onChange:(data:SiteData)=>void}){
 const [rows,setRows]=useState<LogRow[]>([]);const [loading,setLoading]=useState(false);const update=(patch:Partial<SiteData["contactForm"]>)=>onChange({...data,contactForm:{...data.contactForm,...patch}});const load=()=>{setLoading(true);fetch("/api/contact-log").then(r=>r.json()).then(x=>setRows(x.rows||[])).finally(()=>setLoading(false))};useEffect(load,[]);
 const format=(row:LogRow)=>{try{return new Intl.DateTimeFormat("es",{dateStyle:"short",timeStyle:"short",timeZone:row.timezone}).format(new Date(row.createdAt))}catch{return new Date(row.createdAt).toLocaleString("es")}};
 return <section className="editor-card"><div className="card-head"><div><small>Formulario</small><h2>Entrega y registro de consultas</h2><p>El registro conserva como máximo 180 días y elimina automáticamente las entradas anteriores.</p></div><Mail/></div><div className="form-grid"><label className="field"><span>Correo exclusivo de destino</span><input type="email" value={data.contactForm.recipientEmail} onChange={e=>update({recipientEmail:e.target.value})} placeholder="formularios@comercio.com"/></label><label className="field"><span>Zona horaria del registro</span><select value={data.contactForm.timezone} onChange={e=>update({timezone:e.target.value})}><option value="America/Asuncion">Paraguay · Asunción</option><option value="America/Argentina/Buenos_Aires">Argentina · Buenos Aires</option><option value="America/Montevideo">Uruguay · Montevideo</option><option value="America/Sao_Paulo">Brasil · São Paulo</option><option value="UTC">UTC</option></select></label><label className="field"><span>Método de envío</span><select value={data.contactForm.mailTransport} onChange={e=>update({mailTransport:e.target.value as SiteData["contactForm"]["mailTransport"]})}><option value="resend">Servicio web (Resend)</option><option value="phpmail">PHP mail de cPanel</option><option value="smtp_local">SMTP local de cPanel</option><option value="gmail">Gmail SMTP</option></select></label></div><label className="switch-line"><Switch checked={data.contactForm.keepMessageCopy} onCheckedChange={keepMessageCopy=>update({keepMessageCopy})}/>Conservar también una copia del mensaje durante 180 días</label><p className="help-text">Las credenciales y contraseñas se guardan únicamente en el servidor. PHP mail, SMTP local y Gmail usan el gateway seguro configurado por el administrador.</p><div className="log-head"><h3>Uso reciente del formulario</h3><div><button className="control-button secondary" onClick={load} disabled={loading}><RefreshCw/>Actualizar</button><a className="control-button primary" href="/api/contact-log?format=txt"><Download/>Descargar TXT</a></div></div><div className="contact-log">{rows.length?rows.map(row=><div key={row.id}><span>{format(row)}</span><strong>{row.name}</strong><a href={`mailto:${row.email}`}>{row.email}</a><small className={row.delivered?"delivered":"pending"}>{row.delivered?"Correo entregado":"Solo registrado"}</small></div>):<p>No hay usos registrados durante los últimos 180 días.</p>}</div></section>;
}
