"use client";
import type { SiteData } from "@/lib/site-data";
import { ArrowLeft, ArrowRight, GripVertical } from "lucide-react";
import { Checkbox } from "@/components/ui/checkbox";

export default function QuickInfoOrganizer({data,onChange}:{data:SiteData;onChange:(data:SiteData)=>void}){
 const label=(key:string)=>key==="address"?"Dirección":key==="hours"?"Horarios":key==="email"?"Correo":data.phones.find(p=>`phone:${p.id}`===key)?.label||"Teléfono";
 const move=(i:number,dir:number)=>{const j=i+dir;if(j<0||j>=data.quickOrder.length)return;const quickOrder=[...data.quickOrder];[quickOrder[i],quickOrder[j]]=[quickOrder[j],quickOrder[i]];onChange({...data,quickOrder})};
 const layout=(patch:Partial<SiteData["quickLayout"]>)=>onChange({...data,quickLayout:{...data.quickLayout,...patch}});const fixedVisible=(key:"address"|"hours"|"email",visible:boolean)=>onChange({...data,quickVisible:{...data.quickVisible,[key]:visible}});
 return <section className="editor-card"><div className="card-head"><div><small>Tarjeta de información rápida</small><h2>Distribución y orden de los datos</h2><p>Configurá la cuadrícula y el orden de lectura de izquierda a derecha.</p></div></div><div className="quick-layout-controls"><label>Filas<select value={data.quickLayout.rows} onChange={e=>layout({rows:Number(e.target.value)})}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label><label>Columnas<select value={data.quickLayout.columns} onChange={e=>layout({columns:Number(e.target.value)})}>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select></label><label>Ubicación<select value={data.quickLayout.placement} onChange={e=>layout({placement:e.target.value as SiteData["quickLayout"]["placement"]})}><option value="flow">Orden automático</option><option value="center">Centrar última fila</option><option value="manual">Asignar celda</option></select></label></div><div className="module-list">{data.quickOrder.map((key,i)=>{const fixed=key==="address"||key==="hours"||key==="email";const phone=key.startsWith("phone:")?data.phones.find(p=>`phone:${p.id}`===key):null;const checked=fixed?data.quickVisible[key as "address"|"hours"|"email"]:Boolean(phone?.showInQuick);return <div className="module-row quick-position-row" key={key}><GripVertical/><span className="menu-position">{i+1}</span><strong>{label(key)}</strong><label className="check-line"><Checkbox checked={checked} onCheckedChange={v=>fixed&&fixedVisible(key as "address"|"hours"|"email",v===true)}/>{checked?"Visible":"Oculto"}</label>{data.quickLayout.placement==="manual"&&<label className="cell-position">Celda<input value={data.quickLayout.positions[key]||""} placeholder="A1" maxLength={2} onChange={e=>layout({positions:{...data.quickLayout.positions,[key]:e.target.value.toUpperCase()}})}/></label>}<div className="row-actions"><button onClick={()=>move(i,-1)} disabled={i===0} aria-label="Mover a la izquierda"><ArrowLeft/></button><button onClick={()=>move(i,1)} disabled={i===data.quickOrder.length-1} aria-label="Mover a la derecha"><ArrowRight/></button></div></div>})}</div><p className="help-text">En ubicación manual, A1 significa fila A, columna 1; B3 significa fila B, columna 3. Los teléfonos se activan desde “Líneas y canales”.</p></section>;
}
