"use client";
import type { SiteData } from "@/lib/site-data";
import { ArrowDown, ArrowUp, Plus, Trash2 } from "lucide-react";
import { Switch } from "@/components/ui/switch";

export default function ServicesSettings({data,onChange}:{data:SiteData;onChange:(data:SiteData)=>void}){
 const active=data.modules.find(module=>module.key==="services")?.active??true;const setActive=(value:boolean)=>onChange({...data,modules:data.modules.map(module=>module.key==="services"?{...module,active:value}:module)});const update=(i:number,key:"title"|"description",value:string)=>{const services=[...data.services];services[i]={...services[i],[key]:value};onChange({...data,services})};const move=(i:number,dir:number)=>{const next=i+dir;if(next<0||next>=data.services.length)return;const services=[...data.services];[services[i],services[next]]=[services[next],services[i]];onChange({...data,services})};const add=()=>onChange({...data,services:[...data.services,{id:crypto.randomUUID(),title:"Nuevo servicio",description:""}]});const remove=(i:number)=>onChange({...data,services:data.services.filter((_,index)=>index!==i)});
 return <section className="editor-card"><div className="card-head"><div><small>Servicios / Productos</small><h2>Contenido de la sección</h2><p>Administrá la información que aparece en las tarjetas públicas.</p></div><label className="switch-line"><Switch checked={active} onCheckedChange={setActive}/>{active?"Visible":"Oculta"}</label></div><div className="service-content-editor">{data.services.map((service,i)=><article key={service.id}><span className="menu-position">{i+1}</span><label className="field"><span>Título</span><input value={service.title} onChange={e=>update(i,"title",e.target.value)}/></label><label className="field"><span>Descripción</span><textarea value={service.description} onChange={e=>update(i,"description",e.target.value)}/></label><div className="row-actions"><button onClick={()=>move(i,-1)} disabled={i===0} aria-label="Subir servicio"><ArrowUp/></button><button onClick={()=>move(i,1)} disabled={i===data.services.length-1} aria-label="Bajar servicio"><ArrowDown/></button><button onClick={()=>remove(i)} aria-label="Eliminar servicio"><Trash2/></button></div></article>)}</div><button className="control-button primary" onClick={add}><Plus/>Agregar servicio o producto</button></section>;
}
